### ISSUE TITLE
Button Enabled by default

### ISSUE THREAD

**Issue by Maijin** [Zeecka/AperiSolve#11]
Nice new UI, there is a small typo in one of the button, it should all be Disable or if It's truely enabled by default, it should be green. 

Current default output:

<img width="231" alt="image" src="https://user-images.githubusercontent.com/1408600/101370830-477e7e00-38aa-11eb-840a-7dfd55628910.png">

Expected default output:

<img width="228" alt="image" src="https://user-images.githubusercontent.com/1408600/101370856-52d1a980-38aa-11eb-95a6-d8d78e28c58a.png">

Alternative Expected default output:

<img width="194" alt="image" src="https://user-images.githubusercontent.com/1408600/101370892-641ab600-38aa-11eb-876e-f983e270e2b1.png">

**Comment by Zeecka** [comment]
Nice catch :) fixed.
