### ISSUE TITLE
Using multiple files with the same password results in the first file getting used

### ISSUE THREAD

**Issue by nsandler1** [Zeecka/AperiSolve#23]
I needed to use this app with 3 different .jpg files, all with the same password. I uploaded the first file, inputted the password, and submitted the form. Works fine. I try the second jpg file, hit submit, and the results for the previous image is shown. That's weird. I mess around with it by uploading different jpgs, with and without passwords, and noticed that the correct images load as long as I don't use a password I've used in the past. For every file I tried, if I upload one file with the password field filled in, any subsequent file uploaded with the same password will return the results of the first file. 

As soon as I realized there was an issue, I built the app locally and did these tests locally to avoid polluting the production server with my test data.

**Comment by Zeecka** [comment]
Nice catch.
