### ISSUE TITLE
Installing: command not found

### ISSUE THREAD

**Issue by Methylpropane** [Zeecka/AperiSolve#36]
Hello,

When I run **aperisolve example1.png**, I get the following message : _/usr/bin/aperisolve: line 1: Installing: command not found_

Do you have an idea to solve this problem ?

I use Ubuntu 22.04 LTS.

**Comment by Zeecka** [comment]
Fixed with https://github.com/Zeecka/AperiSolve/commit/c49de28412633887ae9fd55ce5acce11f115a800 .
