### ISSUE TITLE
Policy to delete photos after uploading?

### ISSUE THREAD

**Issue by aviv926** [Zeecka/AperiSolve#37]
Hello, I couldn't find the privacy policy or the usage policy on the site so I was wondering what happens after a photo is uploaded through the site? Is it deleted after a certain time or does it stay there forever?
Thanks!

**Comment by Zeecka** [comment]
As defined in https://github.com/Zeecka/AperiSolve/blob/master/backend/modules/garbage_collector.py :
- Top 10 most submitted images are not deleted 
- The other images are deleted after 3 hours

AperiSolve online instance (aperisolve.com) isn't meant for privacy, you can set up your own instance if needed.
