### ISSUE TITLE
Werkzeug leaking python's raised error

### ISSUE THREAD

**Issue by BassoNicolas** [Zeecka/AperiSolve#38]
Greetings,

Background: I attempted to utilize Aperisolve on the web application version. However, when attempting to upload an image, no action occurred, and I discovered that a 500 code was returned upon clicking the "submit" button.

Issue: Werkzeug exposes the Python-generated error and presents a "console locked" form for entering a PIN.

![image](https://user-images.githubusercontent.com/70383324/233067704-52623974-3a37-47f4-825d-003faa1a6b7a.png)

Intended or not, I'm letting you know to make sure :)

**Comment by Zeecka** [comment]
Issue due to no more space on the disc. Fixed/Close.
