### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by BoopEnthusiast** [Zeecka/AperiSolve#43]
Hey you probably know this but I don't see an active issue for it.
![image](https://github.com/Zeecka/AperiSolve/assets/102631339/0f78cbee-cb58-4df8-b713-49d8f75be94f)
Been happening for a few days now and some other friends of mine (We're in New Zealand) have it down too

Can't download and run it either, just says it can't connect to the site

**Comment by Weigurde** [comment]
down on my end too, in canada - seems like the domain expired

**Comment by Zeecka** [comment]
Server is migrating, may be up in few days.

**Comment by BoopEnthusiast** [comment]
Heyl yeah! It's open again and looks dope, glad it got up again I just got two flags for a CTF I'm currently doing within the span of 10 minutes with it, such a useful tool
