### ISSUE TITLE
the container aperisolve_web cannot start normally

### ISSUE THREAD

**Issue by zhanght0311** [Zeecka/AperiSolve#46]
After I build the container using the docker-compose file, I find that the container: `aperisolve_web` cannot start normally, and the error message is as follows:
`from werkzeug.urls import url_quote ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.10/site-packages/werkzeug/urls.py)`
I tried to modify the requirements.txt in the web folder, and added the dependency `werkzeug==2.2.2` on the first line, which can fix this error.
I suggest the author to find out the reason and correct it. @Zeecka

**Comment by Zeecka** [comment]
Related to https://stackoverflow.com/a/77214086

**Comment by Zeecka** [comment]
Fixed with https://github.com/Zeecka/AperiSolve/commit/05059d97571b6afe328e531726dd329dd969817a
