### ISSUE TITLE
Webpage is down

### ISSUE THREAD

**Issue by SergioP3rez** [Zeecka/AperiSolve#5]
Hi,
It looks like something is wrong with the website aperisolve.fr. Actually it shows the server root directory.

Regards!
![Screenshot](https://user-images.githubusercontent.com/10288984/77226065-a57d0100-6b75-11ea-8126-492dd42e7d3f.png)

**Comment by Zeecka** [comment]
My bad, I used Aperisolve yesterday but I did a system upgrade si the server went down. It's back again ;).

I guess you're working on the TamuCTF? 🤔

Zeecka
________________________________

**Comment by SergioP3rez** [comment]
No problem, thank you for get it back!

No, i am not working in this CTF, I am in a stego challenge uploaded in https://atenea.ccn-cert.cni.es/ a spanish webpage that hosts a lot of challenges, maybe you want to try it :)

Thanks again!

**Comment by Zeecka** [comment]
Good to know, I'll have a look :)
