### ISSUE TITLE
Website: /upload results in 500 error

### ISSUE THREAD

**Issue by SebastienTainon** [Zeecka/AperiSolve#53]
Hello,

The website does not work anymore. There is a 500 error on the /upload call so when we upload an image, the results never appear.

Thanks!

**Comment by kzorin52** [comment]
Same

**Comment by Cheerfulbull** [comment]
same here

**Comment by Cheerfulbull** [comment]
Maybe it's necause of https://github.com/Zeecka/AperiSolve/pull/52

**Comment by Cheerfulbull** [comment]
It's not just the uploads too, the old files which are meant to be stored and retrieved by hash aren't working either

**Comment by fadster** [comment]
I seem to be able to upload an image but nothing happens when I click the submit button. I see a few Javascript errors in the console but I'm not sure they're related. Everything was working fine last week though.

**Comment by Zeecka** [comment]
Fixed :)

**Comment by SebastienTainon** [comment]
Thanks!! :+1:
