### ISSUE TITLE
potential bug

### ISSUE THREAD

**Issue by avipars** [Zeecka/AperiSolve#55]
![image](https://github.com/user-attachments/assets/9ca32fae-6c3c-42c5-861f-c5c560d6a21a)

Uploaded a file that was in a compressed folder (and I didn't unzip it)... then the site listed out a bunch of image filenames (presumably from other users?)

**Comment by Zeecka** [comment]
This is a feature. Website keep tracks of files submitted by other users, including passwords.

**Comment by avipars** [comment]
Can it be made into a button perhaps instead? or the idea is to upload a file from within a zip archive and then get this output?

**Comment by Zeecka** [comment]
This is the default behaviour, wether you upload it "from a zip" or not.
