### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by amazonwmn** [Zeecka/AperiSolve#57]
Thank you for a very thorough Steganography tool. I have used it a few times over the years. It seems to be having a problem, though. When I click submit, nothing happens. I tried to download the command line program on mac and when I try to run it, it says "line 8: jq: command not found". I tried in Chrome, Edge, and Safari. On a mac and a pc.

**Comment by Zeecka** [comment]
Fixed on web app.

**Comment by amazonwmn** [comment]
Thank you!
