### ISSUE TITLE
Fail submission shouldn't require reload

### ISSUE THREAD

**Issue by Maijin** [Zeecka/AperiSolve#9]
When submitting a file with incorrect extension, there is no way to upload a new file prior to a reload as it shows the "invalid extension" and disable the upload button.

Fail submission shouldn't require reload and the upload button should be available to resubmit again 👍

**Comment by Zeecka** [comment]
I agree, the same kind of issue happen when a user submit an image and wan't to upload a new one.

**Comment by Zeecka** [comment]
Fixed in new version.
